<%
  rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
  rerun_opts = rerun.to_s.strip.empty? ?
    "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" :
    "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
  std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip"
%>

default: <%= std_opts %> features
wip: --tags <%= ['@wip', '@pdc', '@mt', '@dba'].join(',') %> --wip features
pdc: --tags @pdc --wip features
mt: --tags @mt --wip features
dba: --tags @dba --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip