defaults: &defaults
  adapter: mysql
  pool: 5
  timeout: 5000
  host: localhost
  username: your_application_specific_username
  password: your_application_specific_password

development:
  database: homepage_dev
  <<: *defaults

test: &test
  database: homepage_test
  <<: *defaults

production:
  database: homepage
  <<: *defaults

cucumber:
  <<: *test